import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "welcome_text": "Welcome",
      "welcome_subtext": "Selling Scrap Made Simple: Kabadi at Your Doorstep",
      "login": "Login",
      "logIn": "Log in",
      "logInSubStext": "Enter your registered Phone Number ?",
      "phone": "Phone",
      "enterName": "Your Name",
      "otpVerification": "OTP Verification",
      "otpSubText": "A 6 digit code has been sent to",
      "resend": "Resend",
      "didntReceiveOTP": "Didn’t receive OTP",
      "chooseLanguage": "Choose Language",
      "chooseLanguageSubText": "Pick your Preferred App Language.",
      "english": "English",
      "hindi": "Hindi",
      "selectProceed": "Select & Proceed",
      "yourName": "What’s your Name ?",
      "name": "Full Name",
      "getStarted": "Get Started",
      "myPickupRequests": "My Pickup Requests",
      "scrapPickupReq": "Your Scrap Pickup Requests",
      "upcoming": "Upcoming",
      "previousPickups": "Previous Pickups",
      "pickupID": "Pickup ID :",
      "sellScrap": "Sell Scrap",
      "priceList": "Price List",
      "pickupRequest": "Raise Pickup Request",
      "selectPickupLocation": "Select Pickup Location",
      "pickupLocation": "Pickup Location",
      "yourSavedAddresses": "Your Saved Addresses",
      "addNewAddress": "Add New Address",
      "or": "OR",
      "profile": "Profile",
      "pickupAddress": "Pickup Address",
      "editProfile": "Edit Profile",
      "edit": "Edit",
      "updateProfile": "Update Profile",
      "cancelled": "Cancelled",
      "reschedule": "Reschedule",
      "update": "Update",
      "trackPickupRequest": "Track Pickup Request",
      "trackyourPickup": "Track your Pickup",
      "trackyourPickupSubText": "We are assigning a pickup partner for your Request.",
      "requestReceived": "Request Received",
      "requestAssigned": "Request Assigned",
      "outForPickup": "Out for Pickup",
      "signUp": "Sign Up",
      "signUpTitle": "What’s your Phone Number ?",
      "setLocation": "Set Location",
      "addAddress": "Add Address",
      "addAddressSubTitle": "Add the Complete Address in Detail.",
      "yourLocation": "Your Location",
      "continue_text": "Continue",
      "submit": "Submit"
    },
    'hi_IN': {
      "welcome_text": "स्वागत है",
      "welcome_subtext": "अपने दरवाजे पर रद्दी बेचना आसान बना दिया: कबाड़ी",
      "login": "लॉग इन करें",
      "logIn": "लॉग इन करें",
      "logInSubStext": "अपना पंजीकृत फोन नंबर दर्ज करें ?",
      "phone": "फोन",
      "enterName": "अपना नाम दर्ज करें",
      "otpVerification": "OTP सत्यापन",
      "otpSubText": "एक 6 अंकीय कोड भेजा गया है",
      "resend": "फिर से भेजें",
      "didntReceiveOTP": "OTP प्राप्त नहीं हुआ",
      "chooseLanguage": "भाषा चुनें",
      "chooseLanguageSubText": "अपनी पसंदीदा ऐप भाषा चुनें।",
      "english": "अंग्रेज़ी",
      "hindi": "हिन्दी",
      "selectProceed": "चुनें और आगे बढ़ें",
      "yourName": "आपका नाम क्या है ?",
      "name": "पूरा नाम",
      "getStarted": "शुरू हो जाओ",
      "myPickupRequests": "मेरे पिकअप अनुरोध",
      "scrapPickupReq": "आपके रद्दी पिकअप अनुरोध",
      "upcoming": "आगामी",
      "previousPickups": "पिछले पिकअप",
      "pickupID": "पिकअप आईडी :",
      "sellScrap": "रद्दी बेचें",
      "priceList": "मूल्य सूची",
      "pickupRequest": "पिकअप अनुरोध दर्ज करें",
      "selectPickupLocation": "पिकअप स्थान चुनें",
      "pickupLocation": "पिकअप स्थान",
      "yourSavedAddresses": "आपके सहेजे गए पते",
      "addNewAddress": "नया पता जोड़ें",
      "or": "या",
      "profile": "प्रोफाइल",
      "pickupAddress": "पिकअप पता",
      "editProfile": "प्रोफ़ाइल संपादित करें",
      "edit": "संपादित करें",
      "updateProfile": "प्रोफ़ाइल अपडेट करें",
      "cancelled": "रद्द",
      "reschedule": "पुनः निर्धारित करें",
      "update": "अपडेट करें",
      "trackPickupRequest": "पिकअप अनुरोध का ट्रैक करें",
      "trackyourPickup": "अपने पिकअप को ट्रैक करें",
      "trackyourPickupSubText": "हम आपके अनुरोध के लिए एक पिकअप साथी को नियुक्त कर रहे हैं।",
      "requestReceived": "अनुरोध प्राप्त हुआ",
      "requestAssigned": "अनुरोध को सौंपा गया",
      "outForPickup": "पिकअप के लिए बाहर",
      "signUp": "साइन अप करें",
      "signUpTitle": "आपका फोन नंबर क्या है ?",
      "setLocation": "स्थान सेट करें",
      "addAddress": "पता जोड़ें",
      "addAddressSubTitle": "विस्तार से पूरा पता जोड़ें।",
      "yourLocation": "आपका स्थान",
      "continue_text": "जारी रखें",
      "submit": "प्रस्तुत करें"
    }
    ,
  };
}
